name: PR Build Check

on:
  pull_request:
    branches:
      - dev

jobs:
  build_check:
    name: Validate Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Build
        run: pnpm build
